# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 888bd96a9596913c55ad855f6fe8f4e694bc0c8ef17a4268c11c643af302e6991268ee35dceaa221537d0298309c4c14f6e37264b54c09fec61e652044f79130

test:
  secret_key_base: 47d8930ef9540ccda71dc63554ce457f5f3d94a5238180e3b4021ab5d340ca51937276b05c2e86cb82fb3d87c49252b3e8bb41317718d480ec01cc2f9434eb27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
